[package]
name = "oagain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
thiserror = "1.0.50"
url = "2.5.0"
